FROM ubuntu
MAINTAINER Stephen Stokes ""

#RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

RUN apt-get install -y apache2
RUN apt-get install -y libapache2-mod-proxy-html libxml2-dev
RUN apt-get install -y python2.7

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2$SUFFIX.pid
ENV APACHE_LOCK_DIR /var/lock/apache2$SUFFIX

RUN a2enmod proxy
RUN a2enmod proxy_http
RUN a2enmod proxy_ajp
RUN a2enmod rewrite
RUN a2enmod deflate
RUN a2enmod headers
RUN a2enmod proxy_balancer
RUN a2enmod proxy_connect
RUN a2enmod proxy_html

RUN service apache2 restart

ADD /configfiles /configfiles

RUN cp /configfiles/apache2.conf /etc/apache2/apache2.conf
#CMD python2.7 /application/configcreate.py
RUN cp /configfiles/000-default.conf /etc/apache2/sites-enabled/000-default.conf
#CMD cp /application/000-default.conf /etc/apache2/sites-available/000-default.conf
#CMD cp /application/000-default.conf /etc/apache2/sites-enabled/default
#CMD cp /application/000-default.conf /etc/apache2/sites-available/default

RUN /etc/init.d/apache2 restart


EXPOSE 80

ENTRYPOINT ["/usr/sbin/apache2"]
CMD ["-D", "FOREGROUND"]